# Generated by Django 4.0.2 on 2022-03-27 06:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 27, 6, 59, 30, 606753, tzinfo=utc)),
        ),
    ]
