# Generated by Django 4.0.2 on 2022-04-18 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 18, 9, 39, 26, 989472, tzinfo=utc)),
        ),
    ]
