# Generated by Django 4.0.2 on 2022-04-20 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 20, 17, 50, 19, 355723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(default='received', max_length=50),
        ),
    ]
