# Generated by Django 4.0.2 on 2022-05-11 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_rating_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 6, 35, 59, 186459, tzinfo=utc)),
        ),
    ]
