# Generated by Django 4.0.2 on 2022-05-11 07:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_order_rating_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 7, 13, 40, 278415, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='rating',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
