# Generated by Django 4.0.2 on 2022-05-13 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_order_rating_product_brand_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 13, 9, 28, 2, 424395, tzinfo=utc)),
        ),
    ]
