# Generated by Django 4.0.2 on 2022-05-14 05:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_customer_gender_product_gender_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(1, 'Woody'), (2, 'Floral'), (3, 'Oriental'), (4, 'Fresh')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 14, 5, 9, 4, 364059, tzinfo=utc)),
        ),
    ]
