# Generated by Django 4.0.2 on 2022-05-14 05:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_product_type_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='typee',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 14, 5, 10, 56, 483087, tzinfo=utc)),
        ),
    ]
