# Generated by Django 4.0.2 on 2022-05-15 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_order_date_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type2',
            field=models.IntegerField(choices=[(1, 'Fresh Floral'), (2, 'Fruity Floral'), (3, 'Oriental Floral'), (4, 'Classic Oriental'), (5, 'Woody Oriental'), (6, 'Fresh Water'), (7, 'Fresh Citrus'), (8, 'Fresh Green'), (9, 'Woody Mossy'), (10, 'Woody Smokey'), (11, 'Celebrity Scents'), (12, 'Fresh Oriental')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 15, 9, 6, 30, 897374, tzinfo=utc)),
        ),
    ]
