# Generated by Django 4.0.2 on 2022-05-22 16:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_category_type2_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 22, 16, 6, 53, 555456, tzinfo=utc)),
        ),
    ]
