# Generated by Django 4.0.2 on 2022-05-29 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_customer_password_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 29, 10, 3, 55, 277288, tzinfo=utc)),
        ),
    ]
