# Generated by Django 4.0.2 on 2022-05-29 10:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 29, 10, 29, 39, 85626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=500),
        ),
    ]
