# Generated by Django 4.0.2 on 2022-06-02 19:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_order_rating_alter_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 2, 19, 0, 17, 758031, tzinfo=utc)),
        ),
    ]
